name: prodesys_mobi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+2
  cloud_firestore: ^0.12.9+4
  firebase_storage: ^3.0.6
  moor_flutter: ^2.0.0
  provider: ^3.1.0
  connectivity: ^0.4.4
  rxdart: ^0.22.3
  bloc_pattern: ^2.4.0+2
  progress_dialog: ^1.2.0
  hasura_connect: ^0.1.3
  shared_preferences: ^0.5.3+4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.0.0
  build_runner: 


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg


